name: Validate Project Submission

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  validate:
    if: contains(github.event.issue.title, '[Project Submission]')
    runs-on: ubuntu-latest
    steps:
      - name: Validate submission fields
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = context.payload.issue.body || "";

            const requiredFields = [
              "Project Name:",
              "Repository URL:",
              "Short Description:",
              "Contribution Level:",
              "Areas of Contribution:"
            ];

            let missing = requiredFields.filter(field => !body.includes(field));

            if (missing.length > 0) {
              const warning = [
                "Thank you for your submission!",
                "",
                "It looks like the following required fields are missing:",
                ...missing.map(f => `- ${f}`),
                "",
                "Please edit your issue to include these details. Issues missing required fields will be closed automatically after 7 days."
              ].join("\n");

              await github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: warning
              });

              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["needs-info"]
              });

              core.setFailed("Missing required fields in project submission.");
            } else {
              await github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["valid-submission"]
              });
            }

  auto-close:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'needs-info'
    steps:
      - name: Close issues older than 7 days with 'needs-info' label
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 7
          days-before-close: 0
          stale-issue-message: "This submission has been marked as needing more information and has not been updated in 7 days. Closing this issue. Please feel free to resubmit once all required fields are provided."
          close-issue-message: "Closed due to inactivity."
          only-labels: "needs-info"
