name: Validate and Add Project Submission

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.title, '[Project Submission]')
    steps:
      - name: Validate submission fields
        id: validate
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = context.payload.issue.body || "";

            const requiredFields = [
              "Project Name:",
              "Repository URL:",
              "Short Description:",
              "Contribution Level:",
              "Areas of Contribution:"
            ];

            let missing = requiredFields.filter(field => !body.includes(field));

            if (missing.length > 0) {
              // Comment on issue
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: [
                  "Thank you for your submission!",
                  "",
                  "It looks like the following required fields are missing:",
                  ...missing.map(f => `- ${f}`),
                  "",
                  "Please edit your issue to include these details. Issues missing required fields will be closed automatically after 7 days."
                ].join("\n")
              });

              // Add needs-info label
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["needs-info"]
              });

              require('fs').appendFileSync(
                process.env.GITHUB_OUTPUT,
                `validated=false\n`
              );
            } else {
              // Add valid-submission label
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["valid-submission"]
              });

              // Extract fields
              function extract(field) {
                const regex = new RegExp(`${field}\\s*(.*)`);
                const match = body.match(regex);
                return match ? match[1].trim() : "";
              }

              const name = extract("Project Name:");
              const url = extract("Repository URL:");
              const desc = extract("Short Description:");
              const level = extract("Contribution Level:");

              require('fs').appendFileSync(
                process.env.GITHUB_OUTPUT,
                `validated=true\n` +
                `name=${name}\n` +
                `url=${url}\n` +
                `desc=${desc}\n` +
                `level=${level}\n`
              );
            }

  auto-close:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'needs-info'
    steps:
      - name: Close issues older than 7 days with 'needs-info' label
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 7
          days-before-close: 0
          stale-issue-message: "This submission has been marked as needing more information and has not been updated in 7 days. Closing this issue. Please feel free to resubmit once all required fields are provided."
          close-issue-message: "Closed due to inactivity."
          only-labels: "needs-info"

  create-pr:
    needs: validate
    if: needs.validate.outputs.validated == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Append project entry
        run: |
          FILE="PROJECTS/BEGINNER_PROJECTS.md"
          if [[ "${{ needs.validate.outputs.level }}" =~ [Pp]rofessional ]]; then
            FILE="PROJECTS/PROFESSIONAL_PROJECTS.md"
          fi

          echo "- [${{ needs.validate.outputs.name }}](${{ needs.validate.outputs.url }}) - ${{ needs.validate.outputs.desc }}" >> "$FILE"

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add project: ${{ needs.validate.outputs.name }}"
          branch: add-project-${{ github.event.issue.number }}
          title: "Add project: ${{ needs.validate.outputs.name }}"
          body: |
            This pull request was automatically generated from [issue #${{ github.event.issue.number }}](${{ github.event.issue.html_url }}).

            Project: **${{ needs.validate.outputs.name }}**  
            Level: **${{ needs.validate.outputs.level }}**  
            Repo: ${{ needs.validate.outputs.url }}
