name: Validate and Add Project Submission

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  validate:
    if: contains(github.event.issue.title, '[Project Submission]')
    runs-on: ubuntu-latest
    outputs:
      validated: ${{ steps.validate.outputs.validated }}
      name: ${{ steps.validate.outputs.name }}
      url: ${{ steps.validate.outputs.url }}
      desc: ${{ steps.validate.outputs.desc }}
      level: ${{ steps.validate.outputs.level }}
    steps:
      - name: Check required fields
        id: validate
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = context.payload.issue.body || "";

            // Required fields
            const requiredFields = [
              "Project Name:",
              "Repository URL:",
              "Short Description:",
              "Contribution Level:",
              "Areas of Contribution:"
            ];

            let missing = [];
            for (const field of requiredFields) {
              if (!body.includes(field)) {
                missing.push(field);
              }
            }

            if (missing.length > 0) {
              const message = `⚠️ Thank you for your submission! However, it looks like you are missing the following required fields:\n\n${missing.map(f => `- ${f}`).join("\n")}\n\nPlease edit your issue to include these details.`;
              
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });

              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["needs-info"]
              });

              core.setOutput('validated', 'false');
            } else {
              // Add "valid-submission" label
              await github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["valid-submission"]
              });

              // Improved extraction: get value after 'Field:' up to next line
              function extract(field) {
                const regex = new RegExp(`${field}\\s*(.*)`, 'i');
                const lines = body.split('\n');
                for (const line of lines) {
                  const match = line.match(regex);
                  if (match) {
                    return match[1].trim();
                  }
                }
                return "";
              }

              const name = extract("Project Name:");
              const url = extract("Repository URL:");
              const desc = extract("Short Description:");
              const level = extract("Contribution Level:");

              core.setOutput('validated', 'true');
              core.setOutput('name', name);
              core.setOutput('url', url);
              core.setOutput('desc', desc);
              core.setOutput('level', level);
            }

  create-pr:
    needs: validate
    if: needs.validate.outputs.validated == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set project details as env vars
        run: |
          echo "PROJECT_NAME=${{ needs.validate.outputs.name }}" >> $GITHUB_ENV
          echo "PROJECT_URL=${{ needs.validate.outputs.url }}" >> $GITHUB_ENV
          echo "PROJECT_DESC=${{ needs.validate.outputs.desc }}" >> $GITHUB_ENV
          echo "PROJECT_LEVEL=${{ needs.validate.outputs.level }}" >> $GITHUB_ENV

      - name: Append project entry
        run: |
          FILE="PROJECTS/BEGINNER_PROJECTS.md"
          if [[ "$PROJECT_LEVEL" =~ [Pp]rofessional ]]; then
            FILE="PROJECTS/PROFESSIONAL_PROJECTS.md"
          fi

          echo "- [$PROJECT_NAME]($PROJECT_URL) - $PROJECT_DESC" >> "$FILE"

      - name: Create PR body file
        run: |
          cat > pr_body.txt << EOF
          This pull request was automatically generated from [issue #${{ github.event.issue.number }}](${{ github.event.issue.html_url }}).

          **Project Details:**
          - **Name:** ${PROJECT_NAME}
          - **Level:** ${PROJECT_LEVEL}
          - **Repository:** ${PROJECT_URL}
          - **Description:** ${PROJECT_DESC}
          EOF

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "Add project: ${{ env.PROJECT_NAME }}"
          branch: add-project-${{ github.event.issue.number }}
          title: "Add project: ${{ env.PROJECT_NAME }}"
          body-path: pr_body.txt
